apiVersion: v1
kind: Namespace
metadata:
  name: edwardlecoding
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: assignment3config
  namespace: edwardlecoding
data:
  configValue: snake

---
apiVersion: v1
kind: Service
metadata:
  name: assignment3-service
  namespace: edwardlecoding
spec:
  type: LoadBalancer
  selector:
    app: assignment3
  ports:
    - port: 30000
      protocol: TCP
      name: assignment3-port
      targetPort: public

---
apiVersion: v1
kind: Secret
metadata:
  name: assignment3secret
  namespace: edwardlecoding
data:
  secretValue: c2VjcmV0U25ha2U=

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: assignment3
  namespace: edwardlecoding
spec:
  serviceName: assignment3-service
  selector:
    matchLabels:
      app: assignment3
  template:
    metadata:
      labels:
        app: assignment3
    spec:
      containers:
        - name: app
          image: edwardlecoding/comp4016-assignment3:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 30000
              name: public
          resources:
            limits:
              cpu: 500m
          env:
            - name: envValue
              value: environmentSnake
            - name: SECRET_VALUE
              valueFrom:
                secretKeyRef:
                  name: assignment3secret
                  key: secretValue
            - name: CONFIG_VALUE
              valueFrom:
                configMapKeyRef:
                  name: assignment3config
                  key: configValue
          volumeMounts:
            - name: config
              mountPath: "/config/.env"
              readOnly: true
            - mountPath: "app/assignment3/"
              name: assignment3-pv-storage
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 15
            exec:
              command:
                - "curl"
                - "10.96.0.2:30010/isAlive"
      volumes:
        - name: config
          configMap:
            name: assignment3config
        - name: assignment3-pv-storage
          persistentVolumeClaim:
            claimName: assignment3-pv-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: assignment3-pv-volume
  namespace: edwardlecoding
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/assignment3/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assignment3-pv-claim
  namespace: edwardlecoding
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
